name: Nix flake check

on:
  push:
    branches: [main]
    paths:
      - "**/*.nix"
      - "flake.lock"

  pull_request:
    paths:
      - "**/*.nix"
      - "flake.lock"

jobs:
  flake-check:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/determinate-nix-action@v3.22.2
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check flake
        run: nix flake check --show-trace
